-- NOTE
-- lua require("plenary.test_harness").test_file("tests/test_ccsds.lua")
local util = require("ccsds-hdr.utils")
local conf = require("ccsds-hdr.config")

describe("Module: utils.lua, Function: is_valid_ccsds_hdr_cfgkey", function()
    it("should return valid k/v", function()
        local result = util.is_valid_ccsds_hdr_cfgkey(conf.cfg, "keymaps.encode.mode")
        assert.are.equal(result, conf.cfg.keymaps.encode.mode)
    end)
    it("should not return valid k/v", function()
        assert.has.error(function()
            util.is_valid_ccsds_hdr_cfgkey(conf.cfg, "test1.mode")
        end, "Invalid key: Key 'test1' does not exist.")
    end)
    it("should not return k/v", function()
        assert.has.error(function()
            util.is_valid_ccsds_hdr_cfgkey(conf.cfg, "this.is.a.bad.key")
        end, "Invalid key: Key 'this' does not exist.")
    end)
end)

describe("Module: utils.lua, Function: is_valid_ccsds_hdr_keymap", function()
    local map = { mode = "n", lhs = "<leader>ct99", opt = { desc = "foobar" } }
    vim.keymap.set(map.mode, map.lhs, "", map.opt)
    it("should return valid mapping", function()
        local result = util.is_valid_ccsds_hdr_keymap(map.mode, map.lhs, map.opt.desc)
        assert.are.same(type(result), "table")
        assert.are.equal(#result, 1)
    end)
    it("should not return mapping", function()
        vim.keymap.del(map.mode, map.lhs)
        assert.has.error(function()
            util.is_valid_ccsds_hdr_keymap(map.mode, map.lhs, map.opt.desc)
        end, "Invalid map: Map not found")
    end)
end)

describe("Module: utils.lua, Function: get_buffer_handle_by_name", function()
    it("should return valid handle", function()
        local buf = vim.api.nvim_create_buf(false, true)
        vim.api.nvim_buf_set_name(buf, "foobuff")
        local buf_handle = util.get_buffer_handle_by_name("foobuff")
        assert(buf, buf_handle)
        vim.api.nvim_buf_delete(buf, { force = true })
    end)
    it("should not return handle", function()
        assert.has.error(function()
            util.get_buffer_handle_by_name(123)
        end, "Invalid buffer name: expected a non-empty string")
    end)
    it("should not return handle", function()
        assert.has.error(function()
            util.get_buffer_handle_by_name("")
        end, "Invalid buffer name: expected a non-empty string")
    end)
    it("should not return handle", function()
        assert.has.error(function()
            util.get_buffer_handle_by_name("NonExistentBuffer")
        end, "Error, in retrieving valid buffer")
    end)
end)

describe("Module: utils.lua, Function: convert_input_to_hex_table", function()
    it("should return valid table", function()
        strtable = { "00, 01, 02 0a 0b 0c" }
        hextable = util.convert_input_to_hex_table(strtable[1])
    end)
    it("should return valid table", function()
        strtable = { "00, 01, 02" }
        hextable = util.convert_input_to_hex_table(strtable[1], 6)
    end)
    it("should not return valid table", function()
        assert.has.error(function()
            strtable = { "1" }
            util.convert_input_to_hex_table(strtable[1], 1)
        end, "Invalid argument, arg must be even")
    end)
    it("should not return valid table", function()
        assert.has.error(function()
            strtable = { "01" }
            util.convert_input_to_hex_table(strtable[1], "2")
        end, "Invalid argument, arg must be a number")
    end)
    it("should not return valid table", function()
        assert.has.error(function()
            util.convert_input_to_hex_table(1)
        end, "Invalid argument, arg must be a string")
    end)
end)
